## This file contains code defining two functions:
##"makeCacheMatrix()" and "cacheSolve()".

## The "makeCacheMatrix()" function takes an invertible matrix as an arguement 
## and creates a special matrix object that contains a list of functions
## and the function definitions.  The functions are:
## set()--set the value of the matrix.
## get()--get the the value of the matrix
## setinverse()--set the value of the inverse matrix
## getinverse()--get the value of the inverse matrix

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinverse <- function(inverse) m <<- inverse
  getinverse <- function() m
  list(set = set, get = get, setinverse = setinverse,
       getinverse = getinverse)
}

## The "cacheSolve()" function takes multiple arguements. The first arguement
## is the special matrix generated by "makeCacheMatrix()" and additional 
## anonymous argruements can be included in the call. 
## The first function command extracts and calls the getinverse() function from 
## the list and assigns the value returned to "m".  If "m" has a value
## (i.e. "!is.null(m)") then the value of the cached "m" is returned.  If "m" 
## has a value of "NULL" then the inverse matrix is solved, cached and returned. 
   
cacheSolve <- function(x, ...) {
  m <- x$getinverse()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinverse(m)
  m
}
